# This file is part of the YesWiki Extension groupmanagement.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  groupmanagement:
    authorizedParents: '*'
  groupmanagement_editable_config_params:
    - groupmanagement:
      - authorizedParents