# This file is part of the YesWiki Extension groupmanagement.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  groupmanagement:
    authorizedParents: '*'
  groupmanagement_editable_config_params:
    - groupmanagement:
      - authorizedParents

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Groupmanagement\Service\:
    resource: 'services/*'
    exclude:
     - 'EventDispatcherInterface.php'

  YesWiki\Groupmanagement\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'

  YesWiki\Groupmanagement\Service\EventDispatcher:
    decorates: YesWiki\Core\Service\EventDispatcher
    decoration_on_invalid: null
  
  # Allows to use controllers as services
  YesWiki\Groupmanagement\Controller\:
    resource: 'controllers/*'

  YesWiki\Groupmanagement\Controller\GroupController:
    tags:
      - { name: yeswiki.event_subscriber }
    calls: 
      - registerSubscribers: []